v1.0.1

diff --git a/.github/workflows/prod-cd.yml b/.github/workflows/prod-cd.yml
--- a/.github/workflows/prod-cd.yml
+++ b/.github/workflows/prod-cd.yml
@@ -35,26 +35,16 @@ jobs:
           
           echo "version=$VERSION" >> $GITHUB_OUTPUT
 
-      # - name: Release 생성
-      #   uses: actions/create-release@v1
-      #   env: 
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 'GITHUB_TOKEN'의 권한이 'Read & Write'로 설정되어 있어야 함
-      #   with: 
-      #     tag_name: ${{ steps.extract_version_name.outputs.version }}
-      #     release_name: ${{ steps.extract_version_name.outputs.version }}
-
-
       - name: Create GitHub Release
         run: |
-          curl -X POST \
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
           -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.REPOSITORY_TOKEN }}" \
+          -H "Authorization: Bearer " \
           https://api.github.com/repos/chaewonni/CICDTest/releases \
           -d '{"tag_name":"${{ steps.extract_version_name.outputs.version }}","target_commitish":"main","name":"${{ steps.extract_version_name.outputs.version }}","generate_release_notes":true}'
+          
+          if [ "$response" -ne 201 ]; then
+            echo "GitHub Release failed with status code $response"
+            exit 1
+          fi
 
-        
-          # curl -X POST \
-          # -H "Authorization: token ${{ secrets.REPOSITORY_TOKEN }}" \
-          # -H "Accept: application/vnd.github+json" \
-          # https://api.github.com/repos/${{ github.repository }}/releases \
-          # -d '{"tag_name": "v1.0.0", "name": "Release v1.0.0", "body": "자동 릴리스 생성", "draft": false, "prerelease": false}'
